### ISSUE TITLE
TypeError: Info() got an unexpected keyword argument 'duration'

### ISSUE THREAD

**Issue by oisilener1982** [KwaiVGI/LivePortrait#24]
Everything was working fine before the update. 

D:\AI\LivePortrait\venv\lib\site-packages\torch\nn\modules\conv.py:605: UserWarning: Plan failed with a cudnnException:
CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED
(Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv3d(
Animating... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:02
Concatenating result... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Dump to animations/1111111111111111111--Gradio_3_concat.mp4

Dump to animations/1111111111111111111--Gradio_3.mp4

Traceback (most recent call last):
  File "D:\AI\LivePortrait\venv\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "D:\AI\LivePortrait\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\AI\LivePortrait\venv\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "D:\AI\LivePortrait\venv\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\LivePortrait\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\AI\LivePortrait\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\AI\LivePortrait\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\AI\LivePortrait\venv\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\LivePortrait\src\gradio_pipeline.py", line 64, in execute_video
    gr.Info("Run successfully!", duration=2)
TypeError: Info() got an unexpected keyword argument 'duration'

**Comment by oisilener1982** [comment]
![2](https://github.com/KwaiVGI/LivePortrait/assets/29243313/95eb58ad-8add-460f-91d9-29fbadfec96f)
![1](https://github.com/KwaiVGI/LivePortrait/assets/29243313/3409566a-970f-4bb8-a534-ff79cedaa295)

**Comment by zzzweakman** [comment]
Try to install the newer version gradio:
`pip install gradio==4.36.1`

**Comment by oisilener1982** [comment]
Gradio is already 4.36.1

(venv) D:\AI\LivePortrait>pip list
Package                   Version
------------------------- ------------
aiofiles                  23.2.1
albucore                  0.0.12
albumentations            1.4.10
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
attrs                     23.2.0
certifi                   2024.7.4
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.2.1
cycler                    0.12.1
Cython                    3.0.10
dnspython                 2.6.1
docstring_parser          0.16
email_validator           2.2.0
exceptiongroup            1.2.1
fastapi                   0.111.0
fastapi-cli               0.0.4
ffmpeg                    1.4
ffmpy                     0.3.2
filelock                  3.15.4
flatbuffers               24.3.25
fonttools                 4.53.0
fsspec                    2024.6.1
gradio                    4.36.1
gradio_client             1.0.1
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.4
humanfriendly             10.0
idna                      3.7
imageio                   2.34.2
imageio-ffmpeg            0.5.1
importlib_resources       6.4.0
intel-openmp              2021.4.0
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
lazy_loader               0.4
lmdb                      1.4.1
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.0
mdurl                     0.1.2
mkl                       2021.4.0
mpmath                    1.3.0
networkx                  3.3
numpy                     1.26.4
onnx                      1.16.1
onnxruntime-gpu           1.18.0
opencv-python             4.10.0.84
opencv-python-headless    4.10.0.84
orjson                    3.10.6
packaging                 24.1
pandas                    2.2.2
pillow                    10.4.0
pip                       22.2.1
protobuf                  5.27.2
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.2
pyreadline3               3.4.1
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
requests                  2.32.3
rich                      13.7.1
rpds-py                   0.18.1
ruff                      0.5.0
safetensors               0.4.3
scikit-image              0.24.0
scikit-learn              1.5.1
scipy                     1.13.1
semantic-version          2.10.0
setuptools                63.2.0
shellingham               1.5.4
shtab                     1.7.1
six                       1.16.0
sniffio                   1.3.1
starlette                 0.37.2
sympy                     1.12.1
tbb                       2021.13.0
threadpoolctl             3.5.0
tifffile                  2024.7.2
timm                      1.0.7
tomli                     2.0.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.3.0+cu118
torchaudio                2.3.0+cu118
torchvision               0.18.0+cu118
tqdm                      4.66.4
typer                     0.12.3
typing_extensions         4.12.2
tyro                      0.8.5
tzdata                    2024.1
ujson                     5.10.0
urllib3                   2.2.2
uvicorn                   0.30.1
watchfiles                0.22.0
websockets                11.0.3

[notice] A new release of pip available: 22.2.1 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) D:\AI\LivePortrait>

**Comment by oisilener1982** [comment]
![2](https://github.com/KwaiVGI/LivePortrait/assets/29243313/55251dc8-ec4a-4295-8cb1-2084b24f8797)
![1](https://github.com/KwaiVGI/LivePortrait/assets/29243313/516d08ab-f1db-483f-a05a-b9d8f3127332)

**Comment by D-Mad** [comment]
i fixed it with pip install gradio==4.37.1

**Comment by oisilener1982** [comment]
Thank you so much. The issue was fixed with pip install gradio==4.37.1

**Comment by oisilener1982** [comment]
pip install gradio==4.37.2 
This is the latest and it also works fine

**Comment by zzzweakman** [comment]
We have updated it in the `requirements.txt`. Thanks for your correction! @oisilener1982 @D-Mad
