### ISSUE TITLE
重新安装requirements.txt后显示Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by leetraman822** [KwaiVGI/LivePortrait#272]
你好，今天想尝试有关动物动画的新功能，本来只执行了git pull更新了一下，但是由于运行app_animals.py出现MultiScaleDeformableAttention的错误，所以我尝试使用：
cd src/utils/dependencies/XPose/models/UniPose/ops
python setup.py build install
cd - # equal to cd ../../../../../../../

然后我打算重装liveportrait的conda环境，我删除了很久之前的环境，执行了requirements.txt的安装命令，一切都没有报错。

但安装完成后，无论执行app还是animals，都提示Torch not compiled with CUDA enabled。
我的电脑上安装的有CUDA11.8和12.2, 并且系统设置里也添加了对应的环境变量。
环境变量我并没有手动修改它，因为在我删除虚拟环境后，我立刻重装了requirements，但是现在启动就提示这个错误。

以下是错误信息：

(LivePortrait) F:\StableDiffusion\LivePortrait>python app.py
Traceback (most recent call last):
  File "F:\StableDiffusion\LivePortrait\app.py", line 48, in <module>
    gradio_pipeline = GradioPipeline(
  File "F:\StableDiffusion\LivePortrait\src\gradio_pipeline.py", line 42, in __init__
    super().__init__(inference_cfg, crop_cfg)
  File "F:\StableDiffusion\LivePortrait\src\live_portrait_pipeline.py", line 38, in __init__
    self.live_portrait_wrapper: LivePortraitWrapper = LivePortraitWrapper(inference_cfg=inference_cfg)
  File "F:\StableDiffusion\LivePortrait\src\live_portrait_wrapper.py", line 42, in __init__
    self.appearance_feature_extractor = load_model(inference_cfg.checkpoint_F, model_config, self.device, 'appearance_feature_extractor')
  File "F:\StableDiffusion\LivePortrait\src\utils\helper.py", line 132, in load_model
    model = AppearanceFeatureExtractor(**model_params).to(device)
  File "C:\Users\Administrator\anaconda3\envs\LivePortrait\lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
  File "C:\Users\Administrator\anaconda3\envs\LivePortrait\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\Administrator\anaconda3\envs\LivePortrait\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\Administrator\anaconda3\envs\LivePortrait\lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
  File "C:\Users\Administrator\anaconda3\envs\LivePortrait\lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
  File "C:\Users\Administrator\anaconda3\envs\LivePortrait\lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by zzzweakman** [comment]
@leetraman822  您需要确保nvcc -V输出的版本信息和torch的版本信息一致。如果您之前运行没有问题，并且电脑上已经是cuda 11.8的环境，我推测您应该安装cu118的torch，您可以先创建一个空环境，并[手动安装](https://pytorch.org/get-started/previous-versions/#v230)对应cuda版本pytorch，再安装requirements.txt剩下的环境，之后完成编译MultiScaleDeformableAttention即可运行。

**Comment by TryingToDoBetter25** [comment]
I encountered the same problem, have you solved it？

**Comment by leetraman822** [comment]
> I encountered the same problem, have you solved it？

I'm sorry, the issue hasn't been resolved yet. I've installed LivePortrait on two computers and ran 'git pull' on Computer A to update it. However, afterwards, I encountered this problem. I reinstalled CUDA and Torch, but the issue persists. The environment variables on my computer already include CUDA_PATH, pointing to the relevant CUDA directory. At this moment, I can only consider using the one-click version on Computer A. As for Computer B, I haven't performed the 'git pull' update yet. For now, I'm reluctant to try the new features to avoid encountering the same usability issue after updating...

**Comment by shisunming** [comment]
请问我的显卡不是NVDA的,可以用吗？

**Comment by VaracolacisCrew** [comment]
I was able to fix it by visiting https://pytorch.org/get-started/locally/ and select my matching options.

**Comment by leetraman822** [comment]
> I was able to fix it by visiting https://pytorch.org/get-started/locally/ and select my matching options.

Thanks, I try to input "conda install pytorch" not "pip install", that's solved my problem.
